//USER APIs


//Create Doctor and Patient API
###
POST http://localhost:5000/api/users
content-type: application/json
Accept: application/json

{
  "name": "Gourav",
  "role": "doctor"
}


//List all User and Doctor API
###
GET http://localhost:5000/api/users
content-type: application/json
Accept: application/json



//SLOT CREATE APIs


// Generate Calendar by Doctor API
###
POST http://localhost:5000/api/slots/5
content-type: application/json
Accept: application/json

{
  "timeslots":[
    {
  "start_time": "2025-09-12T09:00:00Z",
  "end_time": "2025-09-12T10:30:00Z",
  "capacity": 3
},
{
  "start_time": "2025-09-12T11:00:00Z",
  "end_time": "2025-09-12T12:30:00Z",
  "capacity": 2
}
  ]
}

//List All Slots of a Doctor API
###
GET http://localhost:5000/api/slots/5
content-type: application/json
Accept: application/json


//Update Slot  by Doctor API
//Defination API ---- http://localhost:5000/api/slots/:doctorId/:slotId
//You can send any or all of these fields
###
PATCH http://localhost:5000/api/slots/5/3
content-type: application/json
Accept: application/json

{
  "capacity": 2
}


//Delete Slot by Doctor API
//Defination API ---- http://localhost:5000/api/slots/:doctorId/:slotId

###
DELETE http://localhost:5000/api/slots/5/2
content-type: application/json
Accept: application/json




// SLOT BOOK APIs


//Patient SlotBook API 
###
POST http://localhost:5000/api/reservations
content-type: application/json
Accept: application/json

{
  "user_id": 2,      //userid from databse
  "timeslot_id": 1   //timeslot id from database
}


//Patient Views Their Reservations API

###
GET http://localhost:5000/api/reservations/user/3
content-type: application/json
Accept: application/json


//Delete Reservatio By Patient API

###
DELETE http://localhost:5000/api/reservations/user/1
content-type: application/json
Accept: application/json
//Id in the api query is the id of reservation from database

